# Rest file to make http calls
@host=http://localhost:3000
@contentType=application/json

### Environment configure
POST {{host}}/api/environment/configure
Accept: {{contentType}}
Content-Type: {{contentType}}

{
    "temperature": 60,
    "humidity": 65,
    "solar-flare": false,
    "storm": false,
    "area-map": [
        [ "dirt", "dirt", "dirt", "water", "dirt" ],
        [ "dirt", "dirt", "water", "water", "water" ],
        [ "dirt", "dirt", "dirt", "water", "dirt" ],
        [ "dirt", "dirt", "dirt", "dirt", "dirt" ],
        [ "dirt", "dirt", "dirt", "dirt", "dirt" ]
    ]
}


### Environment configuration update
PATCH {{host}}/api/environment
Accept: {{contentType}}
Content-Type: {{contentType}}

{
    "storm": false
}

### Get environment config
GET {{host}}/api/environment/status
Accept: {{contentType}}

### Rover configure
POST {{host}}/api/rover/configure
Accept: {{contentType}}
Content-Type: {{contentType}}

{
	"scenarios": [
		{
			"name": "battery-low",
			"conditions": [
				{
					"type": "rover",
					"property": "battery",
					"operator": "lte",
					"value": 2
				}
			],
			"rover": [{ "is": "immobile" }]
		},
		{
			"name": "encountering-water",
			"conditions": [
				{
					"type": "environment",
					"property": "terrain",
					"operator": "eq",
					"value": "water"
				}
			],
			"rover": [
				{
					"performs": {
						"collect-sample": {
							"type": "water-sample",
							"qty": 2
						}
					}
				}
			]
		},
		{
			"name": "encountering-storm",
			"conditions": [
				{
					"type": "environment",
					"property": "storm",
					"operator": "eq",
					"value": true
				}
			],
			"rover": [
				{
					"performs": {
						"item-usage": {
							"type": "storm-shield",
							"qty": 1
						}
					}
				}
			]
		}
	],
	"states": [
		{
			"name": "normal",
			"allowedActions": ["move", "collect-sample"]
		},
		{
			"name": "immobile",
			"allowedActions": ["collect-sample"]
		}
	],
	"deploy-point": {
		"row": 3,
		"column": 1
	},
	"initial-battery": 11,
	"inventory": [
		{
			"type": "storm-shield",
			"quantity": 1,
			"priority": 1
		}
	]
}


### Move Rover
POST {{host}}/api/rover/move
Accept: {{contentType}}
Content-Type: {{contentType}}

{
    "direction": "down"
}


### Get rover status
GET {{host}}/api/rover/status
Accept: : {{contentType}}
